-- -*- mode: lua -*-

go.property('light', vmath.vector4(0, 0, 1000, 1))
go.property('decor', false)

function init(self)
   go.set('#model', 'light', self.light)

   if self.decor then
      factory.create('#decoration_factory', go.get_position())
   end
end

function final(self)
end

function update(self, dt)
end

function fixed_update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
